language: java
install: true
services:
  - mongodb
script: ./travis.sh
dist: focal
before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 21.0.1-open
  - sdk use java 21.0.1-open
#jdk:
#  - openjdk17
