language: java
install: true
services:
  - mongodb
script: ./travis.sh
dist: focal
before_install:
  - sudo systemctl restart mongod.service
  - sleep 10
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 11.0.12-open
  - sdk use java 11.0.12-open
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
#jdk:
#  - openjdk17
